# Generated by Django 3.2.8 on 2022-05-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='text',
        ),
        migrations.AddField(
            model_name='blogs',
            name='paragraph1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogs',
            name='paragraph2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogs',
            name='paragraph3',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
