# Generated by Django 3.2.8 on 2022-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220525_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
